### PR TITLE
Use demo applications when deploying ruby processes from git in integration tests

### PR DESCRIPTION
**Pull request by matej-kupciha**

### CODE REVIEW

**Comment by martiner** [comment]
@matej-kupciha can you please provide some rationale behind this change?

**Comment by matej-kupciha** [comment]
Of course, there are different git repositories for different environments (staging vs production) and the previous git path was not available in production repository. Also IMHO we don't want to use internal paths for public SDK (prodigy-testing). Instead I replaced it with demo applications which we also use in the public API documentation and are more stable.

**Comment by martiner** [comment]
So the demo applications are available in all environments?

Can you please update the commit message accordingly?

**Comment by matej-kupciha** [comment]
Yes, these demo applications are available on all environments. I made sure and tested it yesterday.

Commit message updated (sort of).

**Pull request merged**
