### PR TITLE
Add support for project feature flags

### PR DESCRIPTION
**Pull request by jumarko**

### CODE REVIEW

**Comment by martiner** [comment]
I'm kinda missing `updateProjectFeatureFlag(FeatureFlag) method

**Comment by martiner** [comment]
Can the class `FeatureFlag` be reused for user feature flags as well?

**Comment by jumarko** [comment]
key renamed to name, value renamed to enabled, getters renamed as well.

**Comment by jumarko** [comment]
It seems that it's not possible to reuse FeatureFlag class for user's feature flags, because user feature flags have different structure - check https://confluence.intgdc.com/display/plat/Feature+Flags+Catalog.

**Comment by martiner** [comment]
close #148

**Comment by jumarko** [comment]
Rebased upon the latest upstream version.

**Pull request merged**
