### PR TITLE
1070 Create account with login filled

### LINKED ISSUE #1070: Create account with given login
There is no way (constructor parameter or setter) how to create account with given login.

Please add possibility to create Account with login, possibly using constructor s one does not have to create constructor and then call several set methods.

### PR DESCRIPTION
**Pull request by cipous**
fixes #1070

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/254/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-fossa-scanning-zuul-el7/93/ : SUCCESS in 51s (non-voting)

**Comment by cipous** [comment]
@liry Thanks, please could you let me know once both #1071 and #1064 are released, thank you for driving this!@li

**Comment by liry** [comment]
@cipous FYI both changes are in version 3.9.0+api3 which is ready to be used: https://repo1.maven.org/maven2/com/gooddata/gooddata-java/3.9.0+api3/
https://github.com/gooddata/gooddata-java/releases/tag/gooddata-java-parent-3.9.0+api3

**Comment by cipous** [comment]
I love this approach! Thanks

**Pull request merged**
